/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

#define ADC_BASS_ADDR 		0x40012000UL 	//base address of ADC registers as unsigned long
#define ADC_CR1_REG_OFFSET 	0x04UL 			//offset of the CR1 register
#define ADC_CR1_REG_ADDR 	(ADC_BASS_ADDR + ADC_CR1_REG_OFFSET)
#define RCC_BASE_ADDR 		0x40023800UL 	//base address of RCC registers
#define RCC_APB2_ENR_OFFSET 0x44UL			// offset adress for AOB2 enable register (adc1 is at bit 8)
#define RCC_APB2_ENR_ADDR	(RCC_BASE_ADDR + RCC_APB2_ENR_OFFSET)

int main(void)
{
	// create register pointers
	uint32_t *pRccApb2Reg = (uint32_t*) RCC_APB2_ENR_ADDR; 			//pointer to apb2 clock enable register
	uint32_t *pAdcCr1Reg = (uint32_t*) ADC_CR1_REG_ADDR; 			//pointer to adc1 cr1 register

	//1. enable the peripheral clock
	*pRccApb2Reg |= (1 << 8); // Don't forget pointer dereference	// OR-set the value of the register to 1 shifted to the eighth bit
	//2. modify ADC CR1 register
	*pAdcCr1Reg |= (1 << 8); // Don't forget pointer dereference	// OR-set the value of the register to 1 shifted to the eighth bit

	for(;;);
}
