/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdio.h>

// this is a const data array which is stored in flash memory
char const my_data[]="I love embedded programming!\n";

#define BASE_ADDRESS_OF_SRAM 0x20000000

int main(void)
{
	// fill the location in sram with data from flash
 	for (int i = 0; i < sizeof(my_data); i++)
	{
		*((uint8_t*) BASE_ADDRESS_OF_SRAM +i) = my_data[i];
	}

	// print off contents of flash
//	printf(my_data);

	return 0;
}
